### ISSUE TITLE
Cannot "buy you a coffee" :)

### ISSUE THREAD

**Issue by logical-fallazee** [sixstepsaway/BG3-Modding-Util#1]
Your "buy me a coffee" image here on GitHub is just a link to the image. ;) Not a link to be able to buy you a coffee.

**Comment by sixstepsaway** [comment]
Whoops!! Thank you, I've fixed it and you should find it links to http://ko-fi.com/sixstepsaway now. Thank you for trying to click, finding the problem, and for letting me know!!
