### ISSUE TITLE
Game won't recognize the mods anymore

### ISSUE THREAD

**Issue by Muugitan** [sixstepsaway/BG3-Modding-Util#6]
Heyyy, first of all thank you for this wonderfull tool!
It removed like 80% of my headaches regarding the modded Multiplayer ♥♥♥

But here's the other 20%, maybe you can help me to find the fault and/or a solution:

In general, for me, it works totally fine. I followed the visual guide and tested it on a singleplayer run, all good.
I zipped it up, sent it to my friend and helped her via Teamviewer to get it ready (set the gamepath, etc).
And it worked on first try on our Multiplayer run! (She has to host it, because her internet is a little bit more stable).

But as soon as we quit the game and want to continue playing later, her game gives a warning about missing mods in that savegame and it won't load.
The Utility and the BG3MM show that the mods are loaded (so we have no error log). The game just won't recognize them. Even after restarting the BG3MM and the utility and reload everything.
The only thing that fixed it was to delete the whole folder with the Utility and BG3MM on her computer and "reinstall" it from the .zip i sent her.
And this happens everytime and I believe that's not how it's intend to work..?
And on my computer it doesn't happen, I just can't host our game :/

**Comment by sixstepsaway** [comment]
Is there any possibility your friend moved the folder with the mods or the drive letter changed? 

Where is she putting the folder? Removable hard drive? C drive?

**Comment by Muugitan** [comment]
No she didn't move anything, whenever it happens I jump in on Teamviewer and everything is as it should be :/ 
The mods are on C drive with the folder for "modding stuff" directly on the desktop, the game itself on another internal drive :/

**Comment by Muugitan** [comment]
I accidently closed it 😭

**Comment by sixstepsaway** [comment]
> No she didn't move anything, whenever it happens I jump in on Teamviewer and everything is as it should be :/ The mods are on C drive with the folder for "modding stuff" directly on the desktop, the game itself on another internal drive :/

Things you can test for me, let's see if we can figure this out: 

- [ ] (Back mods up first) When it happens next, get her to go into the Local/Larian Studios/Balder's Gate 3/Mods folder, and assuming the .pak files are in there, right click on one of the "missing" mods and open it with Notepad. It won't show you anything useful if it opens (just gibberish, really), but I want to know if it can open it. What does it say if not? Does the file not exist? Corrupted? etc 
- [ ] Can you try putting the mods somewhere other than Desktop?  C:\BG3 or something would do. 
- [ ] I'm guessing it doesn't do this to yours?
- [ ] Is it all the mods missing from the save or just a few? What mods?

> I accidently closed it 😭

not me trying to find how to reopen it just to realize you already did HAHA

**Comment by Muugitan** [comment]
We'll try that out next time we play and I'll take screenshots etc!
Thank you for the quick replies already ♡

**Comment by sixstepsaway** [comment]
> We'll try that out next time we play and I'll take screenshots etc! Thank you for the quick replies already ♡

No problem! We'll get it sorted. :)

**Comment by Muugitan** [comment]
Okay so when she goes to the Local/Larian Studios/Balder's Gate 3/Mods folder there's only the symlinks and she can't open those with notepad, like she doesn't have the option to when she right-clicks it.
Inside the folder with the utility and mod manager (we called it "moddies") she can open the mod in notepad and gets the gibberish:
![IMG_20240106_064337_779](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155795877/c87a8317-727b-49aa-a684-b644a51a76a7)

With the moddies folder on C:\, loading the mods in the Utility, checking them in BG3MM the savegame can still not be loaded :/

Here' the mods we're using:
![IMG_20240106_064342_169](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155795877/7cdfce3f-b4fe-466d-abde-f59968f1bfd5)

And the missing ones:
![IMG_20240106_064345_548](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155795877/d13a903b-48d0-4d1f-87da-536d1be45f57)


Until now it didn't happen on my computer, I can still run the game and load my savegames. But I didn't host our multiplayer, if that might've something to do with it?

And also, a detail I missed before (i just forgot),
Before she got the game she streamed the game via my steam account and my computer. So she has both our accounts in steam and our steamclouds seem to be a bit messed up. Like my savegames appeared in the cloud of her steam account and vice versa.
Could that be what messes up the modding?
If so, I assume she has to get rid of my account and make a reinstall of the game..?

**Comment by sixstepsaway** [comment]
Is your load order file getting overwritten by something/not saved properly? Maybe it thinks they're not enabled?

Man, you have me so stumped right now LMAO.

No, having two accounts shouldn't cause any problems like this. Hmm...

**Comment by Muugitan** [comment]
I will check that later, I really have to sleep now after the nightshift at work, even tho I want to solve this somehow xD

**Comment by sixstepsaway** [comment]
> I will check that later, I really have to sleep now after the nightshift at work, even tho I want to solve this somehow xD

Sorry I couldn't be more help quicker!! Hope you sleep really well. Let me know what you find.

Tip for the load order: See if the load order file goes down to 1kb after she loads the game. If it does, it's wiping it to "no mods" for some reason.

**Comment by Muugitan** [comment]
Soooooo we found the culprit.

I compared all of our files and orders, and the problem was the load order i saved in the bg3mm.
I called pur specific one PipMoon, but on her end the Utility kept loading the default "Current" with - obviously - no mods in it, because they were saved in PipMoon. 😂😅

We'll give it a proper test when we have time to actually play the game later and then i'll come back to confirm if it really works now! 👌

**Comment by sixstepsaway** [comment]
> Soooooo we found the culprit.
> 
> I compared all of our files and orders, and the problem was the load order i saved in the bg3mm. I called pur specific one PipMoon, but on her end the Utility kept loading the default "Current" with - obviously - no mods in it, because they were saved in PipMoon. 😂😅
> 
> We'll give it a proper test when we have time to actually play the game later and then i'll come back to confirm if it really works now! 👌

Yay!! I hope it's gotten sorted and works! Let me know!

**Comment by Muugitan** [comment]
Ooookay so she has all the mods loaded in "Current" now and we tested the multiplayer and a restart inbetween and everything works fine now!
So it was really that she just couldn't load the premade load order 🤔 

Thanks again for all the suggestions and help!!!
We really appreciate your work ♡♡♡

**Comment by sixstepsaway** [comment]
> Ooookay so she has all the mods loaded in "Current" now and we tested the multiplayer and a restart inbetween and everything works fine now! So it was really that she just couldn't load the premade load order 🤔
> 
> Thanks again for all the suggestions and help!!! We really appreciate your work ♡♡♡

I'm so glad you got it sorted!

Sometimes when there's a mod incompatibility, the game just yeets the entire load order into the sun. It happened to me and the friend I made the tool for a few times - always fun to debug (not). 

I hope you two have so much fun playing the game!!
